config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ghosts
    root  "bob#joe"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ghost.rb
class Ghost < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/bob_controller.rb
class BobController < ApplicationController
    def joe
        
    end
end

app/controllers/ghosts_controller.rb
class GhostsController < ApplicationController
  before_action :set_ghost, only: %i[ show edit update destroy ]

  # GET /ghosts or /ghosts.json
  def index
    @ghosts = Ghost.all
  end

  # GET /ghosts/1 or /ghosts/1.json
  def show
  end

  # GET /ghosts/new
  def new
    @ghost = Ghost.new
  end

  # GET /ghosts/1/edit
  def edit
  end

  # POST /ghosts or /ghosts.json
  def create
    @ghost = Ghost.new(ghost_params)

    respond_to do |format|
      if @ghost.save
        format.html { redirect_to @ghost, notice: "Ghost was successfully created." }
        format.json { render :show, status: :created, location: @ghost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ghost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ghosts/1 or /ghosts/1.json
  def update
    respond_to do |format|
      if @ghost.update(ghost_params)
        format.html { redirect_to @ghost, notice: "Ghost was successfully updated." }
        format.json { render :show, status: :ok, location: @ghost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ghost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ghosts/1 or /ghosts/1.json
  def destroy
    @ghost.destroy
    respond_to do |format|
      format.html { redirect_to ghosts_url, notice: "Ghost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ghost
      @ghost = Ghost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ghost_params
      params.require(:ghost).permit(:name, :age, :volume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bob_helper.rb
module BobHelper
end

app/helpers/ghosts_helper.rb
module GhostsHelper
end

app/views/bob/joe.html.erb
<div class="bgimg">
  <div class="topleft">
  .
  <% if user_signed_in? %>
    <%= current_user.email %> |
    <%= link_to "Log out", destroy_user_session_path, :method=>'delete'%>
  <% else %>
    <%= link_to "login", new_user_session_path %>
  <% end %>
  </div>
  <div class="middle">
    <h1>COMING SOON</h1>
    <hr>
    <p>WordESP</p>
  </div>
  <div class="bottomleft">
    <p>Dirac</p>
  </div>
</div>

app/views/ghosts/_form.html.erb
<%= form_with(model: ghost) do |form| %>
  <% if ghost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ghost.errors.count, "error") %> prohibited this ghost from being saved:</h2>

      <ul>
        <% ghost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.number_field :volume %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ghosts/edit.html.erb
<h1>Editing Ghost</h1>

<%= render 'form', ghost: @ghost %>

<%= link_to 'Show', @ghost %> |
<%= link_to 'Back', ghosts_path %>

app/views/ghosts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ghosts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ghosts.each do |ghost| %>
      <tr>
        <td><%= ghost.name %></td>
        <td><%= ghost.age %></td>
        <td><%= ghost.volume %></td>
        <td><%= link_to 'Show', ghost %></td>
        <td><%= link_to 'Edit', edit_ghost_path(ghost) %></td>
        <td><%= link_to 'Destroy', ghost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ghost', new_ghost_path %>

app/views/ghosts/new.html.erb
<h1>New Ghost</h1>

<%= render 'form', ghost: @ghost %>

<%= link_to 'Back', ghosts_path %>

app/views/ghosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ghost.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @ghost.age %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @ghost.volume %>
</p>

<%= link_to 'Edit', edit_ghost_path(@ghost) %> |
<%= link_to 'Back', ghosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordesp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>